// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CAppBar: typeof import('./components/CAppBar.vue')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CClass: typeof import('./components/CClass.vue')['default']
    CLazy: typeof import('./components/CLazy.vue')['default']
    CSelection: typeof import('./components/CSelection.vue')['default']
    CTimetable: typeof import('./components/CTimetable.vue')['default']
    CTimetableWrapper: typeof import('./components/CTimetableWrapper.vue')['default']
    IonCheckmarkDoneCircleOutline: typeof import('~icons/ion/checkmark-done-circle-outline')['default']
    MdiTimetable: typeof import('~icons/mdi/timetable')['default']
    NotoV1CryingFace: typeof import('~icons/noto-v1/crying-face')['default']
    NotoV1ThinkingFace: typeof import('~icons/noto-v1/thinking-face')['default']
    PhUserCircle: typeof import('~icons/ph/user-circle')['default']
  }
}

export { }
